#include "WaylandTranslator.h"
#include "WaylandProtocolRules.h"

#include <algorithm>
#include <atomic>
#include <chrono>
#include <condition_variable>
#include <mutex>
#include <thread>
#include <vector>

#include <poll.h>
#include <sys/eventfd.h>
#include <unistd.h>

#include <QDebug>

#include <wayland-client.h>
#include <wayland-server.h>

#include "xdg-shell-server-protocol.h"

// Interface tables generated by wayland-scanner (private-code) for the
// forwarded protocols; the core ones come from libwayland itself.
extern "C" {
extern const struct wl_interface zwp_linux_dmabuf_v1_interface;
extern const struct wl_interface wp_viewporter_interface;
extern const struct wl_interface wp_presentation_interface;
extern const struct wl_interface wp_color_manager_v1_interface;
extern const struct wl_interface wp_color_representation_manager_v1_interface;
extern const struct wl_interface wp_fractional_scale_manager_v1_interface;
extern const struct wl_interface wp_single_pixel_buffer_manager_v1_interface;
extern const struct wl_interface wp_content_type_manager_v1_interface;
extern const struct wl_interface wp_linux_drm_syncobj_manager_v1_interface;
extern const struct wl_interface wp_fifo_manager_v1_interface;
}

namespace
{
  const wl_interface* const s_interfaces[] = {
    &wl_compositor_interface,
    &wl_subcompositor_interface,
    &wl_shm_interface,
    &wl_output_interface,
    &zwp_linux_dmabuf_v1_interface,
    &wp_viewporter_interface,
    &wp_presentation_interface,
    &wp_color_manager_v1_interface,
    &wp_color_representation_manager_v1_interface,
    &wp_fractional_scale_manager_v1_interface,
    &wp_single_pixel_buffer_manager_v1_interface,
    &wp_content_type_manager_v1_interface,
    &wp_linux_drm_syncobj_manager_v1_interface,
    &wp_fifo_manager_v1_interface,
  };

  // Dispatcher data on every upstream proxy the translator owns, so an object
  // argument in an upstream event can be told apart from one of Qt's proxies.
  const char s_ownProxy = 0;

  // libwayland's WL_CLOSURE_MAX_ARGS, which is not public.
  const int s_maxArgs = 20;

  // The xdg_wm_base version implemented below (mpv 0.41 binds 6).
  const int s_xdgWmBaseVersion = 6;

  const wl_interface* interfaceByName(const char* name)
  {
    for (const wl_interface* interface : s_interfaces)
    {
      if (strcmp(interface->name, name) == 0)
        return interface;
    }
    return nullptr;
  }

  // One object as seen by mpv (resource) and by the compositor (proxy).
  struct Link
  {
    WaylandTranslator::Private* d;
    const wl_interface* interface;
    wl_resource* resource;
    wl_proxy* proxy;
  };

  struct Global
  {
    WaylandTranslator::Private* d;
    const wl_interface* interface;
    uint32_t upstreamName;
    wl_global* global;
  };

  struct XdgSurface
  {
    WaylandTranslator::Private* d;
    wl_surface* upstreamSurface;
  };

  Link* linkOf(wl_resource* resource)
  {
    return static_cast<Link*>(wl_resource_get_user_data(resource));
  }

  // Calls fn(type, index) for each argument of a message.
  template <typename Fn> void forEachArgument(const wl_message* message, Fn fn)
  {
    int index = 0;
    for (const char* c = message->signature; *c; ++c)
    {
      if (strchr("iufsonah", *c))
        fn(*c, index++);
    }
  }

  // Both libwayland sides duplicate fds when marshalling, and the receiver of
  // a message owns the fds it got.
  void closeFds(const wl_message* message, wl_argument* args)
  {
    forEachArgument(message, [&](char type, int i) {
      if (type == 'h')
        close(args[i].h);
    });
  }

  int forwardRequest(const void*, void* target, uint32_t opcode, const wl_message* message,
                     wl_argument* args);
  int forwardEvent(const void*, void* target, uint32_t opcode, const wl_message* message,
                   wl_argument* args);
  void onResourceDestroyed(wl_resource* resource);
}

///////////////////////////////////////////////////////////////////////////////////////////////////
struct WaylandTranslator::Private
{
  Callbacks callbacks;

  // Upstream: Qt's connection, private queue.
  wl_display* upstream = nullptr;
  wl_event_queue* queue = nullptr;
  wl_registry* registry = nullptr;
  wl_subcompositor* subcompositor = nullptr;
  std::vector<Global*> globals;

  // Downstream: the server mpv connects to.
  wl_display* server = nullptr;
  wl_event_loop* loop = nullptr;
  QByteArray socketName;

  std::thread thread;
  std::atomic<bool> running{ false };
  int wakeFd = -1;
  std::mutex tasksLock;
  std::vector<std::function<void()>> tasks;

  // Translator-thread state: the current toplevel and where it is attached.
  wl_surface* parent = nullptr;
  wl_resource* xdgSurface = nullptr;
  wl_resource* xdgToplevel = nullptr;
  wl_surface* toplevelSurface = nullptr; // upstream proxy of the toplevel's wl_surface
  wl_subsurface* subsurface = nullptr;
  uint32_t configureSerial = 0;
  int width = 0;
  int height = 0;

  void link(wl_resource* resource, wl_proxy* proxy, const wl_interface* interface)
  {
    auto* l = new Link{ this, interface, resource, proxy };
    wl_resource_set_dispatcher(resource, forwardRequest, &s_ownProxy, l, onResourceDestroyed);
    if (proxy)
      wl_proxy_add_dispatcher(proxy, forwardEvent, &s_ownProxy, l);
  }

  // Clients roundtrip after binding or creating objects and expect the
  // compositor's reply by then, but our server answers wl_display.sync at once.
  // Waiting for upstream here forwards the reply before the sync completes.
  void roundtrip() { wl_display_roundtrip_queue(upstream, queue); }

  void post(std::function<void()> task)
  {
    {
      std::lock_guard<std::mutex> lock(tasksLock);
      tasks.push_back(std::move(task));
    }
    uint64_t one = 1;
    if (write(wakeFd, &one, sizeof(one)) < 0)
      qWarning() << "WaylandTranslator: failed to wake translator thread";
  }

  void runTasks()
  {
    std::vector<std::function<void()>> pending;
    {
      std::lock_guard<std::mutex> lock(tasksLock);
      pending.swap(tasks);
    }
    for (auto& task : pending)
      task();
  }

  void attachToplevel()
  {
    if (subsurface || !parent || !toplevelSurface)
      return;

    subsurface = wl_subcompositor_get_subsurface(subcompositor, toplevelSurface, parent);
    wl_subsurface_place_below(subsurface, parent);
    // mpv presents at its own pace; in synchronized mode its frames would only
    // show when Qt commits the parent.
    wl_subsurface_set_desync(subsurface);
    wl_display_flush(upstream);

    if (callbacks.parentCommitNeeded)
      callbacks.parentCommitNeeded();
    if (callbacks.videoSurfaceChanged)
      callbacks.videoSurfaceChanged(true);
  }

  void detachToplevel()
  {
    if (!subsurface)
      return;

    wl_subsurface_destroy(subsurface);
    subsurface = nullptr;
    wl_display_flush(upstream);

    if (callbacks.videoSurfaceChanged)
      callbacks.videoSurfaceChanged(false);
  }

  void sendConfigure()
  {
    if (!xdgToplevel || width <= 0 || height <= 0)
      return;

    // Always fullscreen: the subsurface covers the whole window, and a
    // fullscreen toplevel takes the configured size as is.
    wl_array states;
    wl_array_init(&states);
    *static_cast<uint32_t*>(wl_array_add(&states, sizeof(uint32_t))) = XDG_TOPLEVEL_STATE_FULLSCREEN;
    *static_cast<uint32_t*>(wl_array_add(&states, sizeof(uint32_t))) = XDG_TOPLEVEL_STATE_ACTIVATED;
    xdg_toplevel_send_configure(xdgToplevel, width, height, &states);
    wl_array_release(&states);
    xdg_surface_send_configure(xdgSurface, ++configureSerial);
  }

  void run();
};

namespace
{
  /////////////////////////////////////////////////////////////////////////////////////////////////
  int forwardRequest(const void*, void* target, uint32_t opcode, const wl_message* message,
                     wl_argument* args)
  {
    auto* resource = static_cast<wl_resource*>(target);
    Link* l = linkOf(resource);
    if (!l->proxy)
    {
      closeFds(message, args);
      return 0;
    }

    wl_argument out[s_maxArgs];
    const wl_interface* newInterface = nullptr;
    uint32_t newId = 0;
    forEachArgument(message, [&](char type, int i) {
      out[i] = args[i];
      if (type == 'o' && args[i].o)
      {
        Link* argument = linkOf(reinterpret_cast<wl_resource*>(args[i].o));
        out[i].o = reinterpret_cast<wl_object*>(argument->proxy);
      }
      else if (type == 'n')
      {
        newInterface = message->types[i];
        newId = args[i].n;
        out[i].o = nullptr;
      }
    });

    const bool destructor = WaylandProtocolRules::isDestructorRequest(message);
    if (destructor && reinterpret_cast<wl_surface*>(l->proxy) == l->d->toplevelSurface)
    {
      // The subsurface role object must go before its surface.
      l->d->detachToplevel();
      l->d->toplevelSurface = nullptr;
    }

    wl_proxy* created =
      wl_proxy_marshal_array_flags(l->proxy, opcode, newInterface, wl_proxy_get_version(l->proxy),
                                   destructor ? WL_MARSHAL_FLAG_DESTROY : 0, out);
    closeFds(message, args);

    if (destructor)
    {
      l->proxy = nullptr;
      wl_resource_destroy(resource);
      return 0;
    }

    if (newInterface)
    {
      wl_resource* child = wl_resource_create(wl_resource_get_client(resource), newInterface,
                                              wl_resource_get_version(resource), newId);
      l->d->link(child, created, newInterface);
      if (!WaylandProtocolRules::isPerFrameRequest(l->interface->name, message))
        l->d->roundtrip();
    }
    return 0;
  }

  /////////////////////////////////////////////////////////////////////////////////////////////////
  int forwardEvent(const void*, void* target, uint32_t opcode, const wl_message* message,
                   wl_argument* args)
  {
    auto* proxy = static_cast<wl_proxy*>(target);
    auto* l = static_cast<Link*>(wl_proxy_get_user_data(proxy));
    if (!l->resource)
    {
      closeFds(message, args);
      return 0;
    }

    wl_argument out[s_maxArgs];
    bool foreign = false;
    forEachArgument(message, [&](char type, int i) {
      out[i] = args[i];
      if (type == 'o' && args[i].o)
      {
        // e.g. wl_surface.enter for one of Qt's wl_outputs: not mpv's business.
        auto* argument = reinterpret_cast<wl_proxy*>(args[i].o);
        Link* al = wl_proxy_get_listener(argument) == &s_ownProxy
                     ? static_cast<Link*>(wl_proxy_get_user_data(argument))
                     : nullptr;
        if (al && al->resource)
          out[i].o = reinterpret_cast<wl_object*>(al->resource);
        else
          foreign = true;
      }
      else if (type == 'n')
      {
        auto* created = reinterpret_cast<wl_proxy*>(args[i].o);
        wl_resource* child = wl_resource_create(wl_resource_get_client(l->resource),
                                                message->types[i],
                                                wl_resource_get_version(l->resource), 0);
        l->d->link(child, created, message->types[i]);
        out[i].o = reinterpret_cast<wl_object*>(child);
      }
    });

    if (!foreign)
      wl_resource_post_event_array(l->resource, opcode, out);
    closeFds(message, args);

    if (WaylandProtocolRules::isDestructorEvent(l->interface->name, message))
    {
      wl_proxy_destroy(proxy);
      l->proxy = nullptr;
      wl_resource_destroy(l->resource);
    }
    return 0;
  }

  /////////////////////////////////////////////////////////////////////////////////////////////////
  void onResourceDestroyed(wl_resource* resource)
  {
    Link* l = linkOf(resource);
    if (l->proxy)
    {
      // The client went away without destroying this object: release it upstream.
      if (reinterpret_cast<wl_surface*>(l->proxy) == l->d->toplevelSurface)
      {
        l->d->detachToplevel();
        l->d->toplevelSurface = nullptr;
      }

      int version = static_cast<int>(wl_proxy_get_version(l->proxy));
      int opcode = WaylandProtocolRules::destructorOpcode(l->interface, version);
      if (opcode >= 0)
        wl_proxy_marshal_flags(l->proxy, static_cast<uint32_t>(opcode), nullptr,
                               static_cast<uint32_t>(version), WL_MARSHAL_FLAG_DESTROY);
      else
        wl_proxy_destroy(l->proxy);
    }
    delete l;
  }

  /////////////////////////////////////////////////////////////////////////////////////////////////
  void bindForwarded(wl_client* client, void* data, uint32_t version, uint32_t id)
  {
    auto* g = static_cast<Global*>(data);
    wl_resource* resource = wl_resource_create(client, g->interface, static_cast<int>(version), id);
    auto* proxy = static_cast<wl_proxy*>(
      wl_registry_bind(g->d->registry, g->upstreamName, g->interface, version));
    g->d->link(resource, proxy, g->interface);
    g->d->roundtrip();
  }

  // xdg-shell, implemented locally: mpv's toplevel becomes our subsurface, and
  // everything a window manager would do (title, move, fullscreen) is ignored.
  void destroyResource(wl_client*, wl_resource* resource) { wl_resource_destroy(resource); }

  // A compositor answers state requests with a configure. mpv relies on that:
  // the configure it gets before its first reconfig is only kept as an
  // (unscaled) size hint, the reply to its set_fullscreen gives the real size.
  void reconfigure(wl_client*, wl_resource* resource)
  {
    static_cast<WaylandTranslator::Private*>(wl_resource_get_user_data(resource))->sendConfigure();
  }

  const struct xdg_toplevel_interface s_toplevelImplementation = {
    destroyResource,
    [](wl_client*, wl_resource*, wl_resource*) {},                                  // set_parent
    [](wl_client*, wl_resource*, const char*) {},                                   // set_title
    [](wl_client*, wl_resource*, const char*) {},                                   // set_app_id
    [](wl_client*, wl_resource*, wl_resource*, uint32_t, int32_t, int32_t) {},      // show_window_menu
    [](wl_client*, wl_resource*, wl_resource*, uint32_t) {},                        // move
    [](wl_client*, wl_resource*, wl_resource*, uint32_t, uint32_t) {},              // resize
    [](wl_client*, wl_resource*, int32_t, int32_t) {},                              // set_max_size
    [](wl_client*, wl_resource*, int32_t, int32_t) {},                              // set_min_size
    reconfigure,                                                                    // set_maximized
    reconfigure,                                                                    // unset_maximized
    [](wl_client* c, wl_resource* r, wl_resource*) { reconfigure(c, r); },          // set_fullscreen
    reconfigure,                                                                    // unset_fullscreen
    [](wl_client*, wl_resource*) {},                                                // set_minimized
  };

  void onToplevelDestroyed(wl_resource* resource)
  {
    auto* d = static_cast<WaylandTranslator::Private*>(wl_resource_get_user_data(resource));
    if (d->xdgToplevel != resource)
      return;
    d->detachToplevel();
    d->xdgToplevel = nullptr;
    d->xdgSurface = nullptr;
    d->toplevelSurface = nullptr;
  }

  void getToplevel(wl_client* client, wl_resource* xdgSurfaceResource, uint32_t id)
  {
    auto* xs = static_cast<XdgSurface*>(wl_resource_get_user_data(xdgSurfaceResource));
    WaylandTranslator::Private* d = xs->d;

    wl_resource* resource = wl_resource_create(client, &xdg_toplevel_interface,
                                               wl_resource_get_version(xdgSurfaceResource), id);
    wl_resource_set_implementation(resource, &s_toplevelImplementation, d, onToplevelDestroyed);

    // One video toplevel at a time: a newer VO connection replaces the old one.
    d->detachToplevel();
    d->xdgToplevel = resource;
    d->xdgSurface = xdgSurfaceResource;
    d->toplevelSurface = xs->upstreamSurface;
    d->attachToplevel();
    d->sendConfigure();
  }

  const struct xdg_surface_interface s_xdgSurfaceImplementation = {
    destroyResource,
    getToplevel,
    [](wl_client*, wl_resource* resource, uint32_t, wl_resource*, wl_resource*) {
      wl_resource_post_error(resource, XDG_WM_BASE_ERROR_INVALID_POPUP_PARENT,
                             "popups are not supported");
    },
    [](wl_client*, wl_resource*, int32_t, int32_t, int32_t, int32_t) {}, // set_window_geometry
    [](wl_client*, wl_resource*, uint32_t) {},                         // ack_configure
  };

  const struct xdg_wm_base_interface s_wmBaseImplementation = {
    destroyResource,
    [](wl_client*, wl_resource* resource, uint32_t) {
      wl_resource_post_error(resource, XDG_WM_BASE_ERROR_INVALID_POSITIONER,
                             "positioners are not supported");
    },
    [](wl_client* client, wl_resource* wmBase, uint32_t id, wl_resource* surface) {
      auto* d = static_cast<WaylandTranslator::Private*>(wl_resource_get_user_data(wmBase));
      wl_resource* resource =
        wl_resource_create(client, &xdg_surface_interface, wl_resource_get_version(wmBase), id);
      auto* xs = new XdgSurface{ d, reinterpret_cast<wl_surface*>(linkOf(surface)->proxy) };
      wl_resource_set_implementation(resource, &s_xdgSurfaceImplementation, xs, [](wl_resource* r) {
        delete static_cast<XdgSurface*>(wl_resource_get_user_data(r));
      });
    },
    [](wl_client*, wl_resource*, uint32_t) {}, // pong
  };

  void bindWmBase(wl_client* client, void* data, uint32_t version, uint32_t id)
  {
    auto* d = static_cast<WaylandTranslator::Private*>(data);
    wl_resource* resource =
      wl_resource_create(client, &xdg_wm_base_interface, static_cast<int>(version), id);
    wl_resource_set_implementation(resource, &s_wmBaseImplementation, d, nullptr);
    if (d->callbacks.shellBound)
      d->callbacks.shellBound();
  }

  const wl_registry_listener s_registryListener = {
    [](void* data, wl_registry* registry, uint32_t name, const char* interface, uint32_t version) {
      auto* d = static_cast<WaylandTranslator::Private*>(data);
      if (strcmp(interface, wl_subcompositor_interface.name) == 0)
        d->subcompositor = static_cast<wl_subcompositor*>(
          wl_registry_bind(registry, name, &wl_subcompositor_interface, 1));

      if (!WaylandProtocolRules::isForwardedGlobal(interface))
        return;
      const wl_interface* known = interfaceByName(interface);
      if (!known)
      {
        qWarning() << "WaylandTranslator: no interface table for" << interface;
        return;
      }
      auto* g = new Global{ d, known, name, nullptr };
      int offered = std::min<int>(static_cast<int>(version), known->version);
      g->global = wl_global_create(d->server, known, offered, g, bindForwarded);
      d->globals.push_back(g);
    },
    [](void* data, wl_registry*, uint32_t name) {
      // e.g. an output unplugged. Stop advertising it; the Global stays
      // allocated until shutdown since clients may still be binding it.
      auto* d = static_cast<WaylandTranslator::Private*>(data);
      for (Global* g : d->globals)
      {
        if (g->upstreamName == name && g->global)
        {
          wl_global_remove(g->global);
          g->upstreamName = 0;
        }
      }
    },
  };
}

///////////////////////////////////////////////////////////////////////////////////////////////////
void WaylandTranslator::Private::run()
{
  pollfd fds[2] = { { wl_display_get_fd(upstream), POLLIN, 0 },
                    { wl_event_loop_get_fd(loop), POLLIN, 0 } };

  while (running)
  {
    while (wl_display_prepare_read_queue(upstream, queue) != 0)
      wl_display_dispatch_queue_pending(upstream, queue);
    wl_display_flush(upstream);
    wl_display_flush_clients(server);

    if (poll(fds, 2, -1) > 0 && (fds[0].revents & POLLIN))
      wl_display_read_events(upstream);
    else
      wl_display_cancel_read(upstream);

    if (wl_display_dispatch_queue_pending(upstream, queue) < 0)
    {
      // Qt's connection is gone; Qt reports and handles that itself.
      qWarning() << "WaylandTranslator: upstream connection failed, error"
                 << wl_display_get_error(upstream);
      running = false;
      break;
    }
    wl_event_loop_dispatch(loop, 0);
  }
}

///////////////////////////////////////////////////////////////////////////////////////////////////
WaylandTranslator::WaylandTranslator(wl_display* upstream, Callbacks callbacks)
  : d(new Private)
{
  d->callbacks = std::move(callbacks);
  d->upstream = upstream;
  d->server = wl_display_create();
  d->loop = wl_display_get_event_loop(d->server);

  // A listening socket rather than a one-shot WAYLAND_SOCKET fd: mpv opens more
  // than one connection (its clipboard backend connects first) and reconnects
  // whenever its VO is re-created.
  //
  //
  // Not wl_display_add_socket_auto(): it takes the first "wayland-N" whose lock
  // file is free, and inside a Flatpak sandbox that is the compositor's own
  // socket (a symlink shared by every instance of the app), which it would
  // replace. The same scheme under our own prefix: the first name whose lock
  // is free, which also reuses the socket left by a killed instance.
  for (int i = 0; i < 32 && d->socketName.isEmpty(); ++i)
  {
    QByteArray socket = "jellyfin-desktop-mpv-" + QByteArray::number(i);
    if (wl_display_add_socket(d->server, socket.constData()) == 0)
      d->socketName = socket;
  }
  if (d->socketName.isEmpty())
  {
    qWarning() << "WaylandTranslator: could not create a socket in $XDG_RUNTIME_DIR";
    return;
  }

  d->queue = wl_display_create_queue(upstream);
  auto* wrapper = static_cast<wl_display*>(wl_proxy_create_wrapper(upstream));
  wl_proxy_set_queue(reinterpret_cast<wl_proxy*>(wrapper), d->queue);
  d->registry = wl_display_get_registry(wrapper);
  wl_proxy_wrapper_destroy(wrapper);
  wl_registry_add_listener(d->registry, &s_registryListener, d.get());
  d->roundtrip();

  if (!d->subcompositor)
  {
    qWarning() << "WaylandTranslator: compositor has no wl_subcompositor";
    d->socketName.clear();
    return;
  }

  wl_global_create(d->server, &xdg_wm_base_interface, s_xdgWmBaseVersion, d.get(), bindWmBase);

  d->wakeFd = eventfd(0, EFD_CLOEXEC | EFD_NONBLOCK);
  wl_event_loop_add_fd(d->loop, d->wakeFd, WL_EVENT_READABLE, [](int fd, uint32_t, void* data) {
    uint64_t count;
    if (read(fd, &count, sizeof(count)) >= 0)
      static_cast<Private*>(data)->runTasks();
    return 0;
  }, d.get());

  d->running = true;
  d->thread = std::thread([this] { d->run(); });
  qInfo() << "WaylandTranslator: serving mpv on" << d->socketName;
}

///////////////////////////////////////////////////////////////////////////////////////////////////
WaylandTranslator::~WaylandTranslator()
{
  if (d->thread.joinable())
  {
    d->post([this] { d->running = false; });
    d->thread.join();
  }

  // Destroys every client resource, which releases the upstream objects.
  d->detachToplevel();
  wl_display_destroy_clients(d->server);
  wl_display_destroy(d->server);

  for (Global* g : d->globals)
    delete g;
  if (d->subcompositor)
    wl_subcompositor_destroy(d->subcompositor);
  if (d->registry)
    wl_registry_destroy(d->registry);
  if (d->queue)
  {
    wl_display_flush(d->upstream);
    wl_event_queue_destroy(d->queue);
  }
  if (d->wakeFd >= 0)
    close(d->wakeFd);
}

///////////////////////////////////////////////////////////////////////////////////////////////////
bool WaylandTranslator::isValid() const
{
  return d->running;
}

///////////////////////////////////////////////////////////////////////////////////////////////////
QByteArray WaylandTranslator::socketName() const
{
  return d->socketName;
}

///////////////////////////////////////////////////////////////////////////////////////////////////
void WaylandTranslator::setParentSurface(wl_surface* parent)
{
  if (!d->running)
    return;

  std::mutex doneLock;
  std::condition_variable doneSignal;
  bool done = false;

  d->post([&] {
    if (parent != d->parent)
    {
      d->detachToplevel();
      d->parent = parent;
      d->attachToplevel();
    }
    std::lock_guard<std::mutex> lock(doneLock);
    done = true;
    doneSignal.notify_one();
  });

  // Bounded: if the translator thread died, nothing will run the task.
  std::unique_lock<std::mutex> lock(doneLock);
  if (!doneSignal.wait_for(lock, std::chrono::seconds(2), [&] { return done; }))
    qWarning() << "WaylandTranslator: translator thread did not release the parent surface";
}

///////////////////////////////////////////////////////////////////////////////////////////////////
void WaylandTranslator::configure(int width, int height)
{
  if (!d->running)
    return;

  d->post([=] {
    if (width == d->width && height == d->height)
      return;
    d->width = width;
    d->height = height;
    d->sendConfigure();
  });
}
